name: np_log
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  logging: ^1.2.0

dev_dependencies:
  np_lints:
    path: ../np_lints
