name: np_geocoder
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  http: ^1.1.2
  kdtree:
    git:
      url: https://gitlab.com/nc-photos/kd-tree-dart.git
      ref: 0.2.0-nc-photos-1
  logging: ^1.2.0
  np_codegen:
    path: ../codegen
  np_collection:
    path: ../np_collection
  np_math:
    path: ../np_math
  np_string:
    path: ../np_string
  path: ^1.8.3
  path_provider: ^2.1.3
  sqlite3: ^2.3.0
  to_string:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string-1.0.0
      path: to_string

dev_dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  np_codegen_build:
    path: ../codegen_build
  np_lints:
    path: ../np_lints
  to_string_build:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string_build-1.0.0
      path: to_string_build
