name: np_platform_message_relay
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_codegen:
    path: ../codegen

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  np_codegen_build:
    path: ../codegen_build
  np_lints:
    path: ../np_lints

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_platform_message_relay
        pluginClass: NpPlatformMessageRelayPlugin
      ios:
        pluginClass: NpPlatformMessageRelayPlugin
