name: np_codegen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  np_lints:
    path: ../np_lints
