name: np_api
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.2
  logging: ^1.2.0
  np_codegen:
    path: ../codegen
  np_common:
    path: ../np_common
  np_http:
    path: ../np_http
  np_log:
    path: ../np_log
  np_string:
    path: ../np_string
  to_string:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string-1.0.0
      path: to_string
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  np_codegen_build:
    path: ../codegen_build
  np_lints:
    path: ../np_lints
  test: ^1.22.1
  to_string_build:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string_build-1.0.0
      path: to_string_build
