name: np_universal_storage
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  np_string:
    path: ../np_string
  path: ^1.8.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  np_lints:
    path: ../np_lints
