name: np_db_sqlite
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  copy_with:
    git:
      url: https://gitlab.com/nkming2/dart-copy-with
      path: copy_with
      ref: copy_with-1.3.0
  drift: 2.15.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  logging: ^1.2.0
  np_async:
    path: ../np_async
  np_codegen:
    path: ../codegen
  np_collection:
    path: ../np_collection
  np_common:
    path: ../np_common
  np_datetime:
    path: ../np_datetime
  np_db:
    path: ../np_db
  np_geocoder:
    path: ../np_geocoder
  np_platform_lock:
    path: ../np_platform_lock
  np_platform_util:
    path: ../np_platform_util
  np_string:
    path: ../np_string
  path: ^1.8.3
  path_provider: ^2.1.3
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.21
  to_string:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string-1.0.0
      path: to_string
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  copy_with_build:
    git:
      url: https://gitlab.com/nkming2/dart-copy-with
      path: copy_with_build
      ref: copy_with_build-1.7.0
  drift_dev: 2.15.0
  np_codegen_build:
    path: ../codegen_build
  np_lints:
    path: ../np_lints
  test: ^1.22.1
  to_string_build:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string_build-1.0.0
      path: to_string_build
