name: np_http
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cronet_http: ^1.2.0
  cupertino_http: ^1.3.0
  http: ^1.1.2
  logging: ^1.2.0
  np_platform_util:
    path: ../np_platform_util

dev_dependencies:
  np_lints:
    path: ../np_lints
