name: np_datetime
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  clock: ^1.1.1

dev_dependencies:
  np_lints:
    path: ../np_lints
  test: ^1.21.0
