name: np_gps_map
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.6
  google_maps_flutter: 2.5.3
  google_maps_cluster_manager: 3.1.0
  latlong2: any
  np_async:
    path: ../np_async
  np_collection:
    path: ../np_collection
  np_common:
    path: ../np_common
  np_platform_util:
    path: ../np_platform_util
  rxdart: ^0.27.7
  url_launcher: ^6.1.11

dependency_overrides:
  google_maps_flutter_android: 2.7.0
  google_maps_flutter_platform_interface: 2.5.0

dev_dependencies:
  np_lints:
    path: ../np_lints

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_gps_map
        pluginClass: NpGpsMapPlugin
  assets:
    - assets/
